apiVersion: v1
kind: ConfigMap
metadata:
  name: medifollow-admin-config
  namespace: medifollow-production
data:
  NODE_ENV: "production"
  NEXTAUTH_URL: "https://admin.medifollow.com"
  PUSHER_CLUSTER: "eu"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: medifollow-admin-staging-config
  namespace: medifollow-staging
data:
  NODE_ENV: "staging"
  NEXTAUTH_URL: "https://admin-staging.medifollow.com"
  PUSHER_CLUSTER: "eu"